title: ParentingSimple
description: "Practical parenting tips, child care advice, and family activities to help you raise happy, healthy kids."
url: "https://kkumakkuma.github.io"
baseurl: "/ParentingSimple"
permalink: /:year/:month/:day/:title/
future: true

theme: minima

author:
  name: ParentingSimple
  email: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

google_analytics: "G-JY52FLQ5LE"

exclude:
  - scripts/
  - .github/
  - README.md
  - Gemfile
  - Gemfile.lock
